### ISSUE TITLE
[Bug] Version 1.0 (5) Image Zoom when Upscaling 

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [TheMurusTeam/PromptToImage#8]
Hi, first of all congratulations on the app. I've been using it a lot and really enjoy the results. 

In the latest update you introduced the zoom on the image. It appears that, by default, the image fills all the available area. 

However, when the user upscales the image the following happens: 
<img width="1677" alt="Screenshot 2022-12-31 at 00 03 48" src="https://user-images.githubusercontent.com/34355337/210119023-11871d86-3b9e-4f9e-897e-e468b70e5a85.png">

When the wanted behaviour should be:

<img width="1677" alt="Screenshot 2022-12-31 at 00 05 11" src="https://user-images.githubusercontent.com/34355337/210119050-0dd8e2d7-849a-420c-847a-ec645e798c4c.png">

**Comment by TheMurusTeam** [comment]
I think that if you see a bigger (zoomed in) image after upscale it's because you clicked one of the first 3 buttons (zoom in, zoom out, actual size). Doing so will set a fixed zoom factor, which is preserved after upscale. And because the upscaled image is 4 times bigger, you see it zoomed in.
However if you click the "Zoom to fit" button (the last on the right) then the visible size of the image will be preserved after upscale or de-upscale. In this case the zoom factor is dynamic.
The app remembers the last zoom factor you selected: fixed (first 3 buttons) or dynamic (4th button).

**Comment by JorgeMiguelGomes** [comment]
My proposal was to reset the zoom factor, when upscaling occurs, to fit to view.

**Comment by TheMurusTeam** [comment]
Got it. Done :)

**Comment by JorgeMiguelGomes** [comment]
Thank you. Closing the issue.
